<?php
$PageTitle="Reference";

include_once('header.php');
?>

<? # Add custom HTML content below this line ?>
<div class="container">
    <h1>References</h1>
    <div class="list-group list-group-flush rounded shadow mb-5">
        <a id="ref-1" href="http://www.lcsedu.net/departments/information-technology/chromebook-support" class="list-group-item list-group-item-action bg-transparent-25" target="_blank">1. “Chromebook Support.” <i>LCS</i>, www.lcsedu.net/departments/information-technology/chromebook-support.</a>
        <a id="ref-2" href="http://support.google.com/edu/classroom/answer/6025224?hl=en&ref_topic=7175444" class="list-group-item list-group-item-action bg-transparent-25" target="_blank">2. “Classroom FAQ - Classroom Help.” <i>Google</i>, Google, support.google.com/edu/classroom/answer/6025224?hl=en&ref_topic=7175444.</a>
        <a id="ref-3" href="http://www.cs.odu.edu/~cpi/old/410/orangf20/" class="list-group-item list-group-item-action bg-transparent-25" target="_blank">3. Del Razo, Gabriel, et al. “LittleLEARNERS.” <i>Team Orange</i>, www.cs.odu.edu/~cpi/old/410/orangf20/.</a>
        <a id="ref-4" href="http://www.computerworld.com/article/3234533/android-apps-for-chromebooks-the-essentials.html" class="list-group-item list-group-item-action bg-transparent-25" target="_blank">4. Raphael, JR. “Android Apps for Chromebooks: The Essentials.” <i>Computerworld</i>, Computerworld, 19 Feb. 2019, www.computerworld.com/article/3234533/android-apps-for-chromebooks-the-essentials.html.</a>
        <a id="ref-5" href="http://www.vbschools.com/news/archived_news/2019/chromebooks" class="list-group-item list-group-item-action bg-transparent-25" target="_blank">5. VBCPS. “VBCPS Adds 19,000 Chromebooks to Achieve 1:1.” <i>Virginia Beach City Public Schools</i>, www.vbschools.com/news/archived_news/2019/chromebooks.</a>
        <a id="ref-6" href="http://www.vdh.virginia.gov/coronavirus/coronavirus/covid-19-in-virginia-cases/" class="list-group-item list-group-item-action bg-transparent-25" target="_blank">6. VDH. “COVID 19 Cases In Virginia.” <i>Virginia Department of Health</i>, www.vdh.virginia.gov/coronavirus/coronavirus/covid-19-in-virginia-cases/.</a>
        <a id="ref-7" href="http://www.pewresearch.org/fact-tank/2020/09/10/59-of-u-s-parents-with-lower-incomes-say-their-child-may-face-digital-obstacles-in-schoolwork/" class="list-group-item list-group-item-action bg-transparent-25" target="_blank">7. Vogels, Emily A. “59% Of U.S. Parents with Lower Incomes Say Their Child May Face Digital Obstacles in Schoolwork.” <i>Pew Research Center</i>, Pew Research Center, 10 Sept. 2020, www.pewresearch.org/fact-tank/2020/09/10/59-of-u-s-parents-with-lower-incomes-say-their-child-may-face-digital-obstacles-in-schoolwork/.</a>
        <a id="ref-8" href="http://www.spring.io/web-applications" class="list-group-item list-group-item-action bg-transparent-25" target="_blank">8. “Web Applications with Spring.” <i>Spring</i>, spring.io/web-applications.</a>
        <a id="ref-9" href="http://www.pewresearch.org/fact-tank/2018/10/26/nearly-one-in-five-teens-cant-always-finish-their-homework-because-of-the-digital-divide/" class="list-group-item list-group-item-action bg-transparent-25" target="_blank">9. Anderson, Monica, and Andrew Perrin. “Nearly One-in-Five Teens Can't Always Finish Their Homework Because of the Digital Divide.” <i>Pew Research Center</i>, Pew Research Center, 30 May 2020, www.pewresearch.org/fact-tank/2018/10/26/nearly-one-in-five-teens-cant-always-finish-their-homework-because-of-the-digital-divide/.</a>
        <a id="ref-10" href="http://www.web.archive.org/web/20131010010244/sdu.ictp.it/pinger/pinger.html" class="list-group-item list-group-item-action bg-transparent-25" target="_blank">10. ICTP Science Dissemination Unit, ICTP Science Dissemination. “ICTP-SDU Home Page.” ICTP-SDU: about PingER, web.archive.org/web/20131010010244/sdu.ictp.it/pinger/pinger.html.</a>
        <a id="ref-11" href="http://support.zoom.us/hc/en-us/articles/201362023-System-Requirements-for-PC-Mac-and-Linux" class="list-group-item list-group-item-action bg-transparent-25" target="_blank">11. “System Requirements for Windows, MacOS, and Linux.” <i>Zoom Help Center</i>, support.zoom.us/hc/en-us/articles/201362023-System-Requirements-for-PC-Mac-and-Linux.</a>
        <a id="ref-12" href="http://www.ftc.gov/enforcement/rules/rulemaking-regulatory-reform-proceedings/childrens-online-privacy-protection-rule/" class="list-group-item list-group-item-action bg-transparent-25" target="_blank">12. “Children’s Online Privacy Protection Rule (‘COPPA’).” <i>Federal Trade Commission</i>, 1 Dec. 2020, www.ftc.gov/enforcement/rules/rulemaking-regulatory-reform-proceedings/childrens-online-privacy-protection-rule.</a>
        <a id="ref-13" href="http://www.npr.org/2021/03/05/973373489/npr-ipsos-poll-nearly-one-third-of-parents-may-stick-with-remote-learning/" class="list-group-item list-group-item-action bg-transparent-25" target="_blank">13. Kamenetz, Anya, and Eda Uzunlar. “NPR/Ipsos Poll: Nearly One-Third Of Parents May Stick With Remote Learning.” <i>NPR</i>, NPR, 5 Mar. 2021, www.npr.org/2021/03/05/973373489/npr-ipsos-poll-nearly-one-third-of-parents-may-stick-with-remote-learning.</a>
        <a id="ref-14"href="http://k12.wa.us/policy-funding/equity-and-civil-rights/information-families-civil-rights-washington-schools/section-504-students-disabilities/" class="list-group-item list-group-item-action bg-transparent-25" target="_blank">14. “Section 504 & Students with Disabilities.” <i>Washington Office of Superintendent of Public Instruction</i>, 2021, k12.wa.us/policy-funding/equity-and-civil-rights/information-families-civil-rights-washington-schools/section-504-students-disabilities.</a>
        <a id="ref-15" href="http://cshcn.org/childcare-schools-community/the-504-plan/" class="list-group-item list-group-item-action bg-transparent-25" target="_blank">15. “The 504 Plan.” <i>The Center for Children with Special Needs</i>, 2018, cshcn.org/childcare-schools-community/the-504-plan.</a>
    </div>
</div>
<? # Do not change things below this line ?>
<?php
include_once('footer.php')
?>